apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: 8.8.2
  count: 1
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  http:
    service:
      spec:
        type: LoadBalancer
  elasticsearchRef:
    name: quickstart
