apiVersion: v1
kind: Namespace
metadata:
  name: test1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user1
  namespace: test1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: testadmin
  namespace: test1
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: testadminbinding
  namespace: test1
subjects:
- kind: ServiceAccount
  name: user1
  apiGroup: ""
roleRef:
  kind: Role
  name: testadmin
  apiGroup: ""