apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: zfs.csi.openebs.io
    volume.kubernetes.io/provisioner-deletion-secret-name: ""
    volume.kubernetes.io/provisioner-deletion-secret-namespace: ""
  creationTimestamp: "2023-08-17T08:06:49Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-6bd23479-10b6-4014-81a5-f2f3b73b16a1
  resourceVersion: "23058105"
  uid: cdaca054-71ec-4de9-8fdd-75c724e3cb96
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pd-basic-pd-1
    namespace: tidb-cluster
    resourceVersion: "23058077"
    uid: 6bd23479-10b6-4014-81a5-f2f3b73b16a1
  csi:
    driver: zfs.csi.openebs.io
    fsType: ext4
    volumeAttributes:
      openebs.io/cas-type: localpv-zfs
      openebs.io/poolname: z-pool
      storage.kubernetes.io/csiProvisionerIdentity: 1691736014588-3096-zfs.csi.openebs.io
    volumeHandle: pvc-6bd23479-10b6-4014-81a5-f2f3b73b16a1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: openebs.io/nodeid
          operator: In
          values:
          - node2
  persistentVolumeReclaimPolicy: Delete
  storageClassName: zpool-ext4
  volumeMode: Filesystem
status:
  phase: Bound
