apiVersion: pingcap.com/v1alpha1
kind: TidbNGMonitoring
metadata:
  name: basic
spec:
  clusters:
  - name: basic
    namespace: tidb-cluster
  ngMonitoring:
    requests:
      storage: 1Gi
    version: v6.1.0
    # storageClassName: default
    baseImage: pingcap/ng-monitoring