probeTimeoutSeconds: 5
gitlabUrl: http://gitlab.khaolakonline.com/
runnerToken: "glrt-vxGrMxJNSM-prEwtgQSH"
unregisterRunners: true
terminationGracePeriodSeconds: 3600
concurrent: 5
shutdown_timeout: 0
checkInterval: 30
logFormat: json
rbac:
  create: true
serviceAccount:
  create: true
runners:
  config: |
    [[runners]]
      [runners.kubernetes]
        namespace = "{{.Release.Namespace}}"
        image = "alpine"
        privileged = true
        [[runners.kubernetes.host_aliases]]
          ip = "10.111.0.121"
          hostnames = ["gitlab.thaibevapp.com", "registry.thaibevapp.com", "kas.thaibevapp.com"]
# certsSecretName: gitlab-cert
# hostAliases:
#    - ip: "10.111.0.121"
#      hostnames:
#      - "gitlab.thaibevapp.com"
#      - "registry.thaibevapp.com"
#      - "minio.thaibevapp.com"
#      - "kas.thaibevapp.com"