apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster-poc-2.8.0
spec:
  kafka:
    version: 2.8.0
    logging:
      type: inline
      loggers:
        kafka.root.logger.level: "INFO, WARN, ERROR, DEBUG"
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
         type: scram-sha-512
      - name: external
        port: 9094
        type: loadbalancer
        tls: false
        authentication:
         type: scram-sha-512
        configuration:
          bootstrap:
            loadBalancerIP: 10.111.0.118
          brokers:
          - broker: 0
            loadBalancerIP: 10.111.0.119
          - broker: 1
            loadBalancerIP: 10.111.0.120
          - broker: 2
            loadBalancerIP: 10.111.0.121
    authorization:
      type: simple
    config:
      default.replication.factor: 3
      min.insync.replicas: 3
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.8"
      inter.broker.protocol.version: "2.8"
      log4j.rootLogger: "INFO, stdout, kafkaAppender, Error"
      log4j.logger.org.I0Itec.zkclient.ZkClient: "INFO"
      log4j.logger.org.apache.zookeeper: "INFO"
      log4j.logger.kafka: "INFO, WARN, ERROR"
      log4j.logger.org.apache.kafka: "INFO"
      log4j.logger.kafka.controller: "INFO, controllerAppender"
      log4j.logger.kafka.log.LogCleaner: "INFO, cleanerAppender"
      log4j.logger.state.change.logger: "INFO, stateChangeAppender"
      log4j.logger.kafka.authorizer.logger: "INFO, authorizerAppender"
      log4j.logger.kafka.network.Processor: "WARN, requestAppender"
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yaml
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        class: nfs-client
        deleteClaim: false
    template:
      kafkaContainer:
        env:
        - name: TZ
          value: "Asia/Bangkok"
      pod:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    strimzi.io/cluster: kafka-cluster-poc-02
                    strimzi.io/name: kafka-cluster-poc-kafka
                topologyKey: kubernetes.io/hostname
              weight: 100
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
  zookeeper:
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: zookeeper-metrics
          key: zookeeper-metrics.yaml
    replicas: 3
    config:
      zookeeper.root.logger: "INFO, CONSOLE"
      zookeeper.console.threshold: "INFO"
      zookeeper.log.threshold: "INFO"
      log4j.appender.CONSOLE.Threshold: "INFO"
      log4j.appender.ROLLINGFILE.Threshold: "INFO"
      log4j.appender.TRACEFILE.Threshold: "INFO"
      log4j.rootLogger: "INFO, CONSOLE, WARN, ERROR"
    storage:
      type: persistent-claim
      size: 10Gi
      class: nfs-client
      deleteClaim: false
    template:
      zookeeperContainer:
        env:
        - name: TZ
          value: "Asia/Bangkok"
      pod:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    strimzi.io/cluster: kafka-cluster-poc-02
                    strimzi.io/name: kafka-cluster-zookeeper
                topologyKey: kubernetes.io/hostname
              weight: 100
  entityOperator:
    topicOperator:
      logging:
        type: inline
        loggers:
          rootLogger.level: "INFO, WARN, ERROR"
    userOperator:
      logging:
        type: inline
        loggers:
          rootLogger.level: "INFO, WARN, ERROR"
  cruiseControl:
    logging:
      type: inline
      loggers:
        rootLogger.level: "INFO, DEBUG, ERROR"
