stages: 
  - build
  - deploy

# 
# build_image:
#   stage: build
#   image: docker:24.0.5
#   services:
#     - docker:24.0.5-dind
#   variables:
#     DOCKER_HOST: tcp://docker:2375
#     DOCKER_TLS_CERTDIR: ""
#   before_script:
#     - docker info
#     - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
#   script:
#     - docker pull nginx
#     - docker build -t $IMAGE_NAME:$IMAGE_TAG .
#     - docker push $IMAGE_NAME:$IMAGE_TAG

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"

deploy:
  stage: deploy
  image: ubuntu:latest
  before_script:
    # Install the SSH client
    - apt-get update && apt-get install -y openssh-client
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY root@10.111.0.113 "
        kubectl run cicd --image=${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG} 
        "