# inventory/xxx-cluster/hosts.yaml
all:
  hosts:
    node1:
      ansible_host: node1
      ip: 10.111.0.113
      access_ip: 10.111.0.113
    node2:
      ansible_host: node2
      ip: 10.111.0.114
      access_ip: 10.111.0.114
    node3:
      ansible_host: node3
      ip: 10.111.0.115
      access_ip: 10.111.0.115
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
        node3:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}