## THAIBEV-KAFKAUSER-ADMPPEX ## 

--- 

apiVersion: kafka.strimzi.io/v1beta2 

kind: KafkaUser 

metadata: 

  name: admppex 

  labels: 

    strimzi.io/cluster: kafka-cluster-poc 

spec: 

  authentication: 

    type: scram-sha-512 

  authorization: 

    type: simple 

    acls: 

      # access to kafka topic [Write] 

      - resource: 

          type: topic 

          name: eaadmin 

          patternType: literal 

        operation: All 

        host: "*" 

      # access to kafka group [All] 

      - resource: 

          type: group 

          name: group-eaadmin 

          patternType: literal 

        operation: All 

        host: "*" 