## KAFKAUSER ##
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: test-user
  labels:
    strimzi.io/cluster: kafka-cluster-dev
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      # access to kafka topic [READ]
      - resource:
          type: topic
          name: test-topic
          patternType: literal
        operation: Read
        host: "*"
      # access to kafka group [All]
      - resource:
          type: group
          name: test-group
          patternType: literal
        operation: All
        host: "*"