## KAFKAUSER ##
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: user-test
  labels:
    strimzi.io/cluster: kafka-cluster-poc
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      # access to kafka topic [All]
      - resource:
          type: topic
          name: topic-test
          patternType: literal
        operation: All
        host: "*"
      # access to kafka group [All]
      - resource:
          type: group
          name: group-test
          patternType: literal
        operation: All
        host: "*"