apiVersion: kafka.strimzi.io/v1beta2 
kind: KafkaTopic 
metadata: 
    name: eaadmin 
    labels: 
        strimzi.io/cluster: kafka-cluster-poc 
spec: 
    partitions: 3 
    replicas: 3 
    config: 
        retention.ms: 604800000 
        cleanup.policy: compact, delete 
        compression.type: zstd 